"""Add user_id to resumes

Revision ID: 0d5f3830c35a
Revises: abbbcc2c9b34
Create Date: 2026-07-31 12:52:36.547817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d5f3830c35a'
down_revision = 'abbbcc2c9b34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "user_id",
                sa.Integer(),
                nullable=True
            )
        )
        batch_op.create_foreign_key(
            constraint_name="fk_resumes_user_id",
            referent_table="users",
            local_cols=["user_id"],
            remote_cols=["id"]
        )

    with op.batch_alter_table('user_memories', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_memories', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_resumes_user_id",
            type_="foreignkey"
        )
        batch_op.drop_column('user_id')

        

    # ### end Alembic commands ###
