"""Create help requests table

Revision ID: 206efd90ae72
Revises: f99a0e177fa4
Create Date: 2026-07-28 14:12:55.029393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '206efd90ae72'
down_revision = 'f99a0e177fa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('help_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('helper_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=False),
    sa.Column('preferred_date', sa.Date(), nullable=True),
    sa.Column('preferred_time', sa.Time(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['helper_id'], ['helper.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('help_requests')
    # ### end Alembic commands ###
