"""Add activity url

Revision ID: 44711eeecf0a
Revises: 618f1fe2f322
Create Date: 2026-08-02 22:13:03.541465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44711eeecf0a'
down_revision = '618f1fe2f322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###
