"""upgrade user profile fields

Revision ID: 8dee8b87c544
Revises: 59460e56f791
Create Date: 2026-07-26 17:10:34.977014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dee8b87c544'
down_revision = '59460e56f791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_jobs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'job_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('education', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('experience', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_helper', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('availability', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('completed_tasks', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('completed_tasks')
        batch_op.drop_column('rating')
        batch_op.drop_column('availability')
        batch_op.drop_column('is_helper')
        batch_op.drop_column('experience')
        batch_op.drop_column('education')
        batch_op.drop_column('skills')
        batch_op.drop_column('location')
        batch_op.drop_column('bio')
        batch_op.drop_column('profile_image')

    op.drop_table('saved_jobs')
    # ### end Alembic commands ###
