"""Expand job applications

Revision ID: d54ee9ca859e
Revises: 74a007959fed
Create Date: 2026-07-31 16:01:30.842514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd54ee9ca859e'
down_revision = '74a007959fed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interview_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('resume_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cover_letter', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ai_match_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(
            constraint_name="fk_job_applications_resume_id",
            referent_table="resumes",
            local_cols=["resume_id"],
            remote_cols=["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.drop_constraint("fk_job_applications_resume_id", type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('ai_match_score')
        batch_op.drop_column('source')
        batch_op.drop_column('cover_letter')
        batch_op.drop_column('resume_id')
        batch_op.drop_column('interview_date')

    # ### end Alembic commands ###
